#!/bin/bash

# right click, mute/unmute
if [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
	amixer -D pulse -q sset Capture toggle
# scroll up, increase
elif [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
	amixer -D pulse -q sset Capture ${step}+
# scroll down, decrease
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
	amixer -D pulse -q sset Capture ${step}-
fi

status_line=$(amixer -D pulse get Capture | tail -n 1)
status=$(echo "${status_line}" | grep -wo "on")
volume=$(echo "${status_line}" | cut -d "[" -f 2 | cut -d "%" -f 1)

if [[ "${status}" == "on" ]]; then
	echo "${volume}%"
else
	echo "off"
fi
