import = ["/home/dpaiva/.config/alacritty/alacritty-theme/themes/omni.toml"]

[font]
size = 11

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[window]
opacity = 0.7
title = "Alacritty"

[window.padding]
x = 10
y = 10
